apiVersion: v1
kind: Pod
metadata:
  namespace: petclinic-dev
  labels:
    component: jenkins-agent
spec:
  containers:
  - name: jmeter
    image: silver790310/jmeter:v2
    command:
    - cat
    tty: true
  - name: argocd
    image: payfit/argocd-cli:latest
    command:
    - cat
    envVars:
      envVar:
      - name: ARGOCD_SERVER
      - value: "argocd.example.com"
    tty: true
  serviceAccountName: petclinic-sa
  securityContext:
    runAsUser: 0
  volumes:
    - name: m2
      persistentVolumeClaim:
        claimName: maven-pvc
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
